[project]
name = "bayesh"
version = "0.0.0"
dependencies = [
    "pydantic",
    "pydantic-settings",
    "typer"
]

[tool.setuptools.packages.find]
include = ["bayesh"]

[project.scripts]
bayesh = "bayesh.cli:cli"
