name: "CI"
on: 
  pull_request:
    branches: ["main"]
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build binary
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 1
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Build
        run: make build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/ 
  test-install-script:
    name: Test install script
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get install -y fzf
      - name: Test install script
        run: |
          curl -sSLf https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/install.sh | sh -s -- --url "https://github.com/mads-bisgaard/bayesh/releases/download/v0.0.1/bayesh-v0.0.1-linux-amd64.tar.gz"
          bayesh --version
  bats-tests:
    name: Bats tests
    runs-on: ubuntu-latest
    needs: [build]
    container: madsbis/bayesh-bats-testing:v6
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v5
        with:
          name: build
          path: /usr/local/bin
      - name: Test
        run: |
          chmod +x /usr/local/bin/bayesh
          bats --print-output-on-failure tests
  go-tests:
    name: Go tests
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 1
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Run tests
        run: go test ./src -v
  release:
    name: Release binary
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    needs: [build, bats-tests, go-tests]
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'      
      - name: Build release artifacts
        run: make release
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**
